### ISSUE TITLE
06-15 management group meeting feedback

### ISSUE THREAD

**Issue by 7yl4r** [marinebon/www_marinebon2#19]
We probably want to break some of these out into individual items but I am dropping them there for now:

* [X] Gab: + projects global ARMS MBON, Asia-Pacific MBON - see #33
* [X] Gab: + visual representation to homepage highlighting regional, thematic, etc components. - see #34
* [X] Joana: RE projects: US vs Global MBON highlight may not be politically wise, Gab: "thematic activities" "regional activities". US & AP go under regional. - see #35
* [X] Kat: "projects & programs". Joana: instead of "projects" use "MBONs". Gab: rm projects tab, move stuff to the networks structure page. - see #29
* [x]  RE "products & data" page: prototype display needed ( see #4 )
* [x] See also: [gdoc with feedback from the group]https://docs.google.com/document/d/1NDjpVNLeOC2s16IXPD3eBCdsjPVZWI9xPyoqrNuYkk4/edit?usp=sharing) and  [older gdoc with some notes)[https://docs.google.com/document/d/1Nqyo1sBOw75SwJSZlulzgGlcOvRBZV55P3XsSFfIRr0/edit#heading=h.4i7ojhp]
