### ISSUE TITLE
07-27 site management group TODOs

### ISSUE THREAD

**Issue by 7yl4r** [marinebon/www_marinebon2#24]
* [X] Joana: + join mbon section with details on what joining entails (from original document) - see #27
* [X] publications view on homepage should highlight most recent publications then link to full searchable archive
* [X] merge 1st 4 about us nav sections into 1 - see #28
* [X] links on top nav should go to separate pages - see #29
* [X] news display should also use tiled view & have images for each - see #30
* [x] + link to MBON data portal (as a tool product?)
* [x] get started with a footer - see #31
* [x] fix geobon logo
    * [x] can't see the e
    * [x] should look more like a login button
* [x] borrow homepage design from https://ioos.noaa.gov/ - #32

**Comment by 7yl4r** [comment]
>  get started with a footer

We are ready to create a custom footer using [/layouts/partials/site_footer](https://github.com/marinebon/www_marinebon2/blob/master/layouts/partials/site_footer.html). What should we put in it? I don't recall what was suggested in the meeting.

**Comment by MathewBiddle** [comment]
If we want the site to align with the other ioos.us sites, @mwengren recommended the footers should (if possible):
> have consistent look and feel if possible and match the content at the main ioos.us page (contact info, webmaster email, etc), and require a link to ioos.noaa.gov to more consistently associate ioos.us with ioos.noaa.gov

This isn't a requirement, just recommendation to share. We don't have to align, I don't think...
